version: "3.1"
services:
  postgresdb:
    container_name: "avito-db"
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "avito-db"
      POSTGRES_USER: "avito"
      POSTGRES_PASSWORD: "1qaz2wsx"
